from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


GEMMA_GGUF_BACKEND_ID = "llama_cpp_gguf"
LLAMA_CPP_RELEASE_TAG = "b8832"
LLAMA_CPP_WINDOWS_CUDA12_BIN_ZIP = "llama-b8832-bin-win-cuda-12.4-x64.zip"
LLAMA_CPP_WINDOWS_CUDA12_ZIP = "cudart-llama-bin-win-cuda-12.4-x64.zip"
LLAMA_CPP_WINDOWS_CUDA12_BIN_URL = (
    f"https://github.com/ggml-org/llama.cpp/releases/download/{LLAMA_CPP_RELEASE_TAG}/{LLAMA_CPP_WINDOWS_CUDA12_BIN_ZIP}"
)
LLAMA_CPP_WINDOWS_CUDA12_URL = (
    f"https://github.com/ggml-org/llama.cpp/releases/download/{LLAMA_CPP_RELEASE_TAG}/{LLAMA_CPP_WINDOWS_CUDA12_ZIP}"
)

GEMMA_GGUF_HEADROOM_GB = 1.0


@dataclass(frozen=True)
class GemmaGgufProfile:
    id: str
    label: str
    repo_id: str
    model_filename: str
    mmproj_filename: str
    quantization: str
    approx_model_gb: float
    approx_mmproj_gb: float
    effective_params_label: str
    recommended_ctx: int
    quality_rank: int
    min_total_vram_gb: float

    @property
    def approx_total_gb(self) -> float:
        return float(self.approx_model_gb) + float(self.approx_mmproj_gb)

    @property
    def model_url(self) -> str:
        return f"https://huggingface.co/{self.repo_id}/resolve/main/{self.model_filename}"

    @property
    def mmproj_url(self) -> str:
        return f"https://huggingface.co/{self.repo_id}/resolve/main/{self.mmproj_filename}"


GEMMA_GGUF_PROFILES: tuple[GemmaGgufProfile, ...] = (
    GemmaGgufProfile(
        id="e2b_ud_iq2_m",
        label="Gemma 4 E2B UD-IQ2_M",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-UD-IQ2_M.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-IQ2_M",
        approx_model_gb=2.29,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=1536,
        quality_rank=625,
        min_total_vram_gb=3.5,
    ),
    GemmaGgufProfile(
        id="e2b_ud_iq3_xxs",
        label="Gemma 4 E2B UD-IQ3_XXS",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-UD-IQ3_XXS.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-IQ3_XXS",
        approx_model_gb=2.37,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=1536,
        quality_rank=635,
        min_total_vram_gb=3.5,
    ),
    GemmaGgufProfile(
        id="e2b_ud_q2_k_xl",
        label="Gemma 4 E2B UD-Q2_K_XL",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-UD-Q2_K_XL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-Q2_K_XL",
        approx_model_gb=2.40,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=1536,
        quality_rank=630,
        min_total_vram_gb=3.5,
    ),
    GemmaGgufProfile(
        id="e2b_q3_k_s",
        label="Gemma 4 E2B Q3_K_S",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-Q3_K_S.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q3_K_S",
        approx_model_gb=2.45,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=1536,
        quality_rank=645,
        min_total_vram_gb=3.75,
    ),
    GemmaGgufProfile(
        id="e2b_q3_k_m",
        label="Gemma 4 E2B Q3_K_M",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-Q3_K_M.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q3_K_M",
        approx_model_gb=2.54,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=1536,
        quality_rank=650,
        min_total_vram_gb=3.75,
    ),
    GemmaGgufProfile(
        id="e2b_ud_q3_k_xl",
        label="Gemma 4 E2B UD-Q3_K_XL",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-UD-Q3_K_XL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-Q3_K_XL",
        approx_model_gb=2.92,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=1536,
        quality_rank=640,
        min_total_vram_gb=4.25,
    ),
    GemmaGgufProfile(
        id="e2b_iq4_xs",
        label="Gemma 4 E2B IQ4_XS",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-IQ4_XS.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="IQ4_XS",
        approx_model_gb=2.98,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=695,
        min_total_vram_gb=4.5,
    ),
    GemmaGgufProfile(
        id="e2b_iq4_nl",
        label="Gemma 4 E2B IQ4_NL",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-IQ4_NL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="IQ4_NL",
        approx_model_gb=3.04,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=700,
        min_total_vram_gb=4.5,
    ),
    GemmaGgufProfile(
        id="e2b_q4_0",
        label="Gemma 4 E2B Q4_0",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-Q4_0.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q4_0",
        approx_model_gb=3.04,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=705,
        min_total_vram_gb=4.5,
    ),
    GemmaGgufProfile(
        id="e2b_q4_k_s",
        label="Gemma 4 E2B Q4_K_S",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-Q4_K_S.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q4_K_S",
        approx_model_gb=3.04,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=710,
        min_total_vram_gb=4.5,
    ),
    GemmaGgufProfile(
        id="e2b_q4_k_m",
        label="Gemma 4 E2B Q4_K_M",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-Q4_K_M.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q4_K_M",
        approx_model_gb=3.11,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=720,
        min_total_vram_gb=4.5,
    ),
    GemmaGgufProfile(
        id="e2b_q4_1",
        label="Gemma 4 E2B Q4_1",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-Q4_1.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q4_1",
        approx_model_gb=3.15,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=715,
        min_total_vram_gb=4.5,
    ),
    GemmaGgufProfile(
        id="e2b_ud_q4_k_xl",
        label="Gemma 4 E2B UD-Q4_K_XL",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-UD-Q4_K_XL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-Q4_K_XL",
        approx_model_gb=3.17,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=660,
        min_total_vram_gb=4.75,
    ),
    GemmaGgufProfile(
        id="e2b_q5_k_s",
        label="Gemma 4 E2B Q5_K_S",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-Q5_K_S.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q5_K_S",
        approx_model_gb=3.32,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=735,
        min_total_vram_gb=5.0,
    ),
    GemmaGgufProfile(
        id="e2b_q5_k_m",
        label="Gemma 4 E2B Q5_K_M",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-Q5_K_M.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q5_K_M",
        approx_model_gb=3.36,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=740,
        min_total_vram_gb=5.0,
    ),
    GemmaGgufProfile(
        id="e4b_ud_iq2_m",
        label="Gemma 4 E4B UD-IQ2_M",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-UD-IQ2_M.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-IQ2_M",
        approx_model_gb=3.53,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=1536,
        quality_rank=830,
        min_total_vram_gb=4.75,
    ),
    GemmaGgufProfile(
        id="e4b_ud_iq3_xxs",
        label="Gemma 4 E4B UD-IQ3_XXS",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-UD-IQ3_XXS.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-IQ3_XXS",
        approx_model_gb=3.70,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=1536,
        quality_rank=850,
        min_total_vram_gb=5.0,
    ),
    GemmaGgufProfile(
        id="e4b_ud_q2_k_xl",
        label="Gemma 4 E4B UD-Q2_K_XL",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-UD-Q2_K_XL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-Q2_K_XL",
        approx_model_gb=3.74,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=1536,
        quality_rank=840,
        min_total_vram_gb=5.0,
    ),
    GemmaGgufProfile(
        id="e2b_ud_q5_k_xl",
        label="Gemma 4 E2B UD-Q5_K_XL",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-UD-Q5_K_XL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-Q5_K_XL",
        approx_model_gb=4.29,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=670,
        min_total_vram_gb=5.25,
    ),
    GemmaGgufProfile(
        id="e2b_q6_k",
        label="Gemma 4 E2B Q6_K",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-Q6_K.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q6_K",
        approx_model_gb=4.50,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=760,
        min_total_vram_gb=5.75,
    ),
    GemmaGgufProfile(
        id="e4b_q3_k_s",
        label="Gemma 4 E4B Q3_K_S",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-Q3_K_S.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q3_K_S",
        approx_model_gb=3.86,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=1536,
        quality_rank=870,
        min_total_vram_gb=5.0,
    ),
    GemmaGgufProfile(
        id="e2b_ud_q6_k_xl",
        label="Gemma 4 E2B UD-Q6_K_XL",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-UD-Q6_K_XL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-Q6_K_XL",
        approx_model_gb=4.71,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=680,
        min_total_vram_gb=5.75,
    ),
    GemmaGgufProfile(
        id="e4b_q3_k_m",
        label="Gemma 4 E4B Q3_K_M",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-Q3_K_M.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q3_K_M",
        approx_model_gb=4.06,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=1536,
        quality_rank=880,
        min_total_vram_gb=5.25,
    ),
    GemmaGgufProfile(
        id="e4b_ud_q3_k_xl",
        label="Gemma 4 E4B UD-Q3_K_XL",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-UD-Q3_K_XL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-Q3_K_XL",
        approx_model_gb=4.56,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=1536,
        quality_rank=860,
        min_total_vram_gb=5.75,
    ),
    GemmaGgufProfile(
        id="e2b_q8_0",
        label="Gemma 4 E2B Q8_0",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-Q8_0.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q8_0",
        approx_model_gb=5.05,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=780,
        min_total_vram_gb=6.25,
    ),
    GemmaGgufProfile(
        id="e4b_iq4_xs",
        label="Gemma 4 E4B IQ4_XS",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-IQ4_XS.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="IQ4_XS",
        approx_model_gb=4.72,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=940,
        min_total_vram_gb=5.75,
    ),
    GemmaGgufProfile(
        id="e2b_ud_q8_k_xl",
        label="Gemma 4 E2B UD-Q8_K_XL",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-UD-Q8_K_XL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-Q8_K_XL",
        approx_model_gb=5.27,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=690,
        min_total_vram_gb=6.5,
    ),
    GemmaGgufProfile(
        id="e4b_iq4_nl",
        label="Gemma 4 E4B IQ4_NL",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-IQ4_NL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="IQ4_NL",
        approx_model_gb=4.84,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=950,
        min_total_vram_gb=5.9,
    ),
    GemmaGgufProfile(
        id="e4b_q4_0",
        label="Gemma 4 E4B Q4_0",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-Q4_0.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q4_0",
        approx_model_gb=4.84,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=960,
        min_total_vram_gb=5.9,
    ),
    GemmaGgufProfile(
        id="e4b_q4_k_s",
        label="Gemma 4 E4B Q4_K_S",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-Q4_K_S.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q4_K_S",
        approx_model_gb=4.84,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=965,
        min_total_vram_gb=5.9,
    ),
    GemmaGgufProfile(
        id="e4b_q4_k_m",
        label="Gemma 4 E4B Q4_K_M",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-Q4_K_M.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q4_K_M",
        approx_model_gb=4.98,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=980,
        min_total_vram_gb=6.0,
    ),
    GemmaGgufProfile(
        id="e4b_q4_1",
        label="Gemma 4 E4B Q4_1",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-Q4_1.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q4_1",
        approx_model_gb=5.07,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=970,
        min_total_vram_gb=6.1,
    ),
    GemmaGgufProfile(
        id="e4b_ud_q4_k_xl",
        label="Gemma 4 E4B UD-Q4_K_XL",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-UD-Q4_K_XL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-Q4_K_XL",
        approx_model_gb=5.10,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=900,
        min_total_vram_gb=6.1,
    ),
    GemmaGgufProfile(
        id="e4b_q5_k_s",
        label="Gemma 4 E4B Q5_K_S",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-Q5_K_S.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q5_K_S",
        approx_model_gb=5.40,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=995,
        min_total_vram_gb=6.5,
    ),
    GemmaGgufProfile(
        id="e4b_q5_k_m",
        label="Gemma 4 E4B Q5_K_M",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-Q5_K_M.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q5_K_M",
        approx_model_gb=5.48,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=1000,
        min_total_vram_gb=6.5,
    ),
    GemmaGgufProfile(
        id="e4b_ud_q5_k_xl",
        label="Gemma 4 E4B UD-Q5_K_XL",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-UD-Q5_K_XL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-Q5_K_XL",
        approx_model_gb=6.65,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=910,
        min_total_vram_gb=7.75,
    ),
    GemmaGgufProfile(
        id="e4b_q6_k",
        label="Gemma 4 E4B Q6_K",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-Q6_K.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q6_K",
        approx_model_gb=7.07,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=1020,
        min_total_vram_gb=8.25,
    ),
    GemmaGgufProfile(
        id="e4b_ud_q6_k_xl",
        label="Gemma 4 E4B UD-Q6_K_XL",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-UD-Q6_K_XL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-Q6_K_XL",
        approx_model_gb=7.46,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=920,
        min_total_vram_gb=8.5,
    ),
    GemmaGgufProfile(
        id="e4b_q8_0",
        label="Gemma 4 E4B Q8_0",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-Q8_0.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="Q8_0",
        approx_model_gb=8.19,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=1050,
        min_total_vram_gb=9.5,
    ),
    GemmaGgufProfile(
        id="e4b_ud_q8_k_xl",
        label="Gemma 4 E4B UD-Q8_K_XL",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-UD-Q8_K_XL.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="UD-Q8_K_XL",
        approx_model_gb=8.66,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=2048,
        quality_rank=930,
        min_total_vram_gb=9.75,
    ),
    GemmaGgufProfile(
        id="e2b_bf16",
        label="Gemma 4 E2B BF16",
        repo_id="unsloth/gemma-4-E2B-it-GGUF",
        model_filename="gemma-4-E2B-it-BF16.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="BF16",
        approx_model_gb=9.31,
        approx_mmproj_gb=0.99,
        effective_params_label="2.3B effective",
        recommended_ctx=2048,
        quality_rank=800,
        min_total_vram_gb=10.5,
    ),
    GemmaGgufProfile(
        id="e4b_bf16",
        label="Gemma 4 E4B BF16",
        repo_id="unsloth/gemma-4-E4B-it-GGUF",
        model_filename="gemma-4-E4B-it-BF16.gguf",
        mmproj_filename="mmproj-BF16.gguf",
        quantization="BF16",
        approx_model_gb=15.1,
        approx_mmproj_gb=0.99,
        effective_params_label="4.5B effective",
        recommended_ctx=4096,
        quality_rank=1100,
        min_total_vram_gb=16.5,
    ),
    GemmaGgufProfile(
        id="e26b_q4_k_m",
        label="Gemma 4 26B A4B Q4_K_M",
        repo_id="ggml-org/gemma-4-26B-A4B-it-GGUF",
        model_filename="gemma-4-26B-A4B-it-Q4_K_M.gguf",
        mmproj_filename="mmproj-gemma-4-26B-A4B-it-f16.gguf",
        quantization="Q4_K_M",
        approx_model_gb=16.8,
        approx_mmproj_gb=1.19,
        effective_params_label="25B params",
        recommended_ctx=4096,
        quality_rank=1150,
        min_total_vram_gb=18.5,
    ),
    GemmaGgufProfile(
        id="e31b_q4_k_m",
        label="Gemma 4 31B Q4_K_M",
        repo_id="ggml-org/gemma-4-31B-it-GGUF",
        model_filename="gemma-4-31B-it-Q4_K_M.gguf",
        mmproj_filename="mmproj-gemma-4-31B-it-f16.gguf",
        quantization="Q4_K_M",
        approx_model_gb=18.7,
        approx_mmproj_gb=1.2,
        effective_params_label="31B params",
        recommended_ctx=4096,
        quality_rank=1300,
        min_total_vram_gb=20.5,
    ),
    GemmaGgufProfile(
        id="e26b_q8_0",
        label="Gemma 4 26B A4B Q8_0",
        repo_id="ggml-org/gemma-4-26B-A4B-it-GGUF",
        model_filename="gemma-4-26B-A4B-it-Q8_0.gguf",
        mmproj_filename="mmproj-gemma-4-26B-A4B-it-f16.gguf",
        quantization="Q8_0",
        approx_model_gb=26.9,
        approx_mmproj_gb=1.19,
        effective_params_label="25B params",
        recommended_ctx=4096,
        quality_rank=1200,
        min_total_vram_gb=29.0,
    ),
    GemmaGgufProfile(
        id="e31b_q8_0",
        label="Gemma 4 31B Q8_0",
        repo_id="ggml-org/gemma-4-31B-it-GGUF",
        model_filename="gemma-4-31B-it-Q8_0.gguf",
        mmproj_filename="mmproj-gemma-4-31B-it-f16.gguf",
        quantization="Q8_0",
        approx_model_gb=32.6,
        approx_mmproj_gb=1.2,
        effective_params_label="31B params",
        recommended_ctx=4096,
        quality_rank=1350,
        min_total_vram_gb=34.5,
    ),
    GemmaGgufProfile(
        id="e26b_f16",
        label="Gemma 4 26B A4B F16",
        repo_id="ggml-org/gemma-4-26B-A4B-it-GGUF",
        model_filename="gemma-4-26B-A4B-it-f16.gguf",
        mmproj_filename="mmproj-gemma-4-26B-A4B-it-f16.gguf",
        quantization="F16",
        approx_model_gb=50.5,
        approx_mmproj_gb=1.19,
        effective_params_label="25B params",
        recommended_ctx=4096,
        quality_rank=1250,
        min_total_vram_gb=52.5,
    ),
    GemmaGgufProfile(
        id="e31b_f16",
        label="Gemma 4 31B F16",
        repo_id="ggml-org/gemma-4-31B-it-GGUF",
        model_filename="gemma-4-31B-it-f16.gguf",
        mmproj_filename="mmproj-gemma-4-31B-it-f16.gguf",
        quantization="F16",
        approx_model_gb=61.4,
        approx_mmproj_gb=1.2,
        effective_params_label="31B params",
        recommended_ctx=4096,
        quality_rank=1400,
        min_total_vram_gb=64.0,
    ),
)


def gemma_profile_by_id(profile_id: str) -> GemmaGgufProfile | None:
    for profile in GEMMA_GGUF_PROFILES:
        if profile.id == str(profile_id or "").strip():
            return profile
    return None


def gemma_profile_options() -> tuple[GemmaGgufProfile, ...]:
    return GEMMA_GGUF_PROFILES


def choose_best_gemma_profile(total_vram_gb: float | None, free_vram_gb: float | None = None) -> GemmaGgufProfile:
    total = max(0.0, float(total_vram_gb or 0.0))
    free = max(0.0, float(free_vram_gb or 0.0))
    usable = max(0.0, total - GEMMA_GGUF_HEADROOM_GB)
    if free > 0.0:
        usable = min(usable or free, free + 0.5)
    candidates = [
        profile
        for profile in GEMMA_GGUF_PROFILES
        if total >= profile.min_total_vram_gb and usable >= profile.approx_total_gb
    ]
    if candidates:
        return sorted(candidates, key=lambda item: (item.quality_rank, item.approx_total_gb), reverse=True)[0]
    for profile in reversed(GEMMA_GGUF_PROFILES):
        if usable >= profile.approx_total_gb:
            return profile
    return GEMMA_GGUF_PROFILES[-1]


def gemma_profile_install_dir(models_dir: Path, profile: GemmaGgufProfile) -> Path:
    return Path(models_dir) / "gemma_gguf" / profile.id


def gemma_profile_model_path(models_dir: Path, profile: GemmaGgufProfile) -> Path:
    return gemma_profile_install_dir(models_dir, profile) / profile.model_filename


def gemma_profile_mmproj_path(models_dir: Path, profile: GemmaGgufProfile) -> Path:
    return gemma_profile_install_dir(models_dir, profile) / profile.mmproj_filename


def gemma_profile_is_installed(models_dir: Path, profile: GemmaGgufProfile) -> bool:
    return gemma_profile_model_path(models_dir, profile).is_file() and gemma_profile_mmproj_path(models_dir, profile).is_file()
